// <auto-generated />
using System;
using CapacityTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapacityTracker.Api.Migrations
{
    [DbContext(typeof(CapacityDbContext))]
    [Migration("20260715020501_SprintJWinConversionRevenue")]
    partial class SprintJWinConversionRevenue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapacityTracker.Api.Models.ActualHours", b =>
                {
                    b.Property<Guid>("ActualHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChargeableHours")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActualHoursId");

                    b.HasIndex("PersonId", "Month")
                        .IsUnique();

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Allocation", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlanLineItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("AllocationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WeekStart");

                    b.HasIndex("PersonId", "ProjectId", "WeekStart")
                        .IsUnique();

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FieldChanged")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Industry")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RelationshipPartner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ClientId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.EngagementDocument", b =>
                {
                    b.Property<Guid>("EngagementDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("EngagementDocumentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EngagementDocuments");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BillRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CostRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IndustryExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Practice")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Rank")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Skills")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("StaffingPreferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("UtilizationTarget")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyCapacityHours")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("Email");

                    b.HasIndex("ManagerId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PlanLineItem", b =>
                {
                    b.Property<Guid>("PlanLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BillRateOverride")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ClientRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CostRateOverride")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Geography")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Organization")
                        .HasColumnType("int");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rank")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SubcontractorFirm")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PlanLineItemId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PricingPlanId");

                    b.ToTable("PlanLineItems");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PlanWeekHours", b =>
                {
                    b.Property<Guid>("PlanWeekHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("PlanLineItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("PlanWeekHoursId");

                    b.HasIndex("PlanLineItemId", "WeekStart")
                        .IsUnique();

                    b.ToTable("PlanWeekHours");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Practice", b =>
                {
                    b.Property<Guid>("PracticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultUtilizationTarget")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("PracticeId");

                    b.HasIndex("LeadId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PricingPlan", b =>
                {
                    b.Property<Guid>("PricingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BlendedRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("FixedFee")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid?>("MdOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Practice")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PricingModel")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RecoverableExpenses")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TechnologyFees")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WonAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WonBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PricingPlanId");

                    b.HasIndex("MdOwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PricingPlans");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BaselineLockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("BaselineLockedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("DealValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("DeliveryLeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EngagementType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("WinProbability")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("DeliveryLeadId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.ProjectBaselineLine", b =>
                {
                    b.Property<Guid>("ProjectBaselineLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.HasKey("ProjectBaselineLineId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectBaselineLines");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.RateCardEntry", b =>
                {
                    b.Property<Guid>("RateCardEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BillRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("RateCardEntryId");

                    b.HasIndex("Rank", "Geography", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("RateCardEntries");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.RevenuePhase", b =>
                {
                    b.Property<Guid>("RevenuePhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<bool>("IsInferred")
                        .HasColumnType("bit");

                    b.Property<int>("Layer")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<Guid>("PricingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RevenuePhaseId");

                    b.HasIndex("PricingPlanId", "Layer", "PeriodStart")
                        .IsUnique();

                    b.ToTable("RevenuePhases");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.RevenueSetup", b =>
                {
                    b.Property<Guid>("RevenueSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("ContractRph")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FeeStructure")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceFrequency")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InvoiceScheduleNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsInferred")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tcv")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("RevenueSetupId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("RevenueSetups");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.ActualHours", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Allocation", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "Person")
                        .WithMany("Allocations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapacityTracker.Api.Models.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.EngagementDocument", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Person", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PlanLineItem", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CapacityTracker.Api.Models.PricingPlan", "Plan")
                        .WithMany("LineItems")
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PlanWeekHours", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.PlanLineItem", "LineItem")
                        .WithMany("WeekHours")
                        .HasForeignKey("PlanLineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineItem");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Practice", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PricingPlan", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "MdOwner")
                        .WithMany()
                        .HasForeignKey("MdOwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CapacityTracker.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MdOwner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Project", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Person", "DeliveryLead")
                        .WithMany()
                        .HasForeignKey("DeliveryLeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeliveryLead");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.ProjectBaselineLine", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Project", "Project")
                        .WithMany("BaselineLines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.RevenuePhase", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.PricingPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.RevenueSetup", b =>
                {
                    b.HasOne("CapacityTracker.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Person", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PlanLineItem", b =>
                {
                    b.Navigation("WeekHours");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.PricingPlan", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("CapacityTracker.Api.Models.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("BaselineLines");
                });
#pragma warning restore 612, 618
        }
    }
}
