name: Deploy Dev

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      params_file: infra/main.dev.bicepparam
    secrets: inherit
