name: Deploy Prod

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      params_file: infra/main.prod.bicepparam
    secrets: inherit
